# .github/workflows/code_cleanup.yml
name: Code Cleanup & Lint

on:
  workflow_run:
    workflows: ["Auto-format Python code with Black"]
    types:
      - completed

jobs:
  cleanup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install lint tools
        run: pip install vulture flake8 flake8-todo flake8-comments

      - name: Run Vulture
        run: vulture .

      - name: Run Flake8
        run: flake8 .
