name: Code Cleanup & Lint

on:
  workflow_run:
    workflows: ["Auto-format Python code with Black"]
    types:
      - completed

jobs:
  cleanup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install vulture flake8 flake8-todo flake8-comments

      - name: Run Vulture (detect unused code)
        run: vulture . || true

      - name: Run Flake8
        run: flake8 . --ignore=E501,W503

