name: Unused Code & Comment Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-cleanup-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install vulture flake8

    - name: Check for unused code with Vulture
      run: |
        vulture . > unused_code_report.txt || true
        cat unused_code_report.txt

    - name: Check for commented-out code with flake8
      run: |
        flake8 . --extend-ignore=E501 --per-file-ignores="__init__.py:F401" > flake8_report.txt || true
        cat flake8_report.txt
